### PR TITLE
Change 2D flux write from ASCII dump to netcdf-4 + gcc fix

### PR DESCRIPTION
**Pull request by Pheosics**
RAM 2D Flux was written every hour as an ascii dump if requested. Turned it into a configurable time based write with a compressed netcdf-4 output to conserve space.

New versions of GCC would not compile the iri87 and msis86 code. Removed their calls and stopped the compiler from linking against them as they were not needed

### CODE REVIEW

**Comment by drsteve** [comment]
Can you elaborate on how iri and msis are not needed? And how the compilation failed (presumably compiler flag issues)?
Obviously they have been written in as something optional. Is this a temporary removal? And should more recent versions be used if/when they get reinstated?

**Comment by Pheosics** [comment]
They are written in such a way that they are no longer complaint with modern fortran compilers. It would be possible to include them if we used standards flags, but that opens up several other issues.

The older versions of iri and msis are not needed as the newer versions are included. They were included in the past so that the user could choose to use the newer or older versions.

**Comment by drsteve** [comment]
Okay, that's much clearer from the full context - the diffs didn't really highlight the fact that you essentially set the new versions as the defaults and just removed the option of using the older versions. I'm curious, given the rationale, about why you just commented out the lines around this instead of removing them. I mean, we're under version control here, and leaving a commented control block in the code seems to suggest that it's either important to know about or might be subject to further revision.
Did you want to clean the commented lines out?
Also, I don't see where this touches code allowing the setting of those models... is the option still present/supported and just not used?

**Comment by Pheosics** [comment]
As far as I can tell none of that code is actually used in the default version of RAM-SCB, it was included by request so that it could be used in future work and for other programs. Ideally we would remove IRI and MSIS completely as they are not our code and simply have plugins designed to interface with them when necessary, but that would required a substantial rewrite

**Comment by drsteve** [comment]
Okay, let's leave how this is included as an open item for discussion, and I'll merge the changes.

**Pull request merged**
