### PR TITLE
ModRamCoul: Changed sign tests for double precision variables

### PR DESCRIPTION
**Pull request by Pheosics**
Using equalities when working in double precision can be problamatic. I
have changed all of the equalities to a cooresponding greater/less than
and slightly updated the if statements to a more modern syntax

### CODE REVIEW

**Comment by drsteve** [comment]
These are all just checks for sign?
I've updated the PR title so it's a bit more informative.

This seems fine, but it made me wonder... It seems like the integer sign (`ISIGN`) is used it two ways:
- To multiply floats.
- To increment/decrement an integer.

Why not use `sign` for that case?
```
ISIGN = int(sign(1.0_dp, CccolE(K))) ! ISIGN has sign of CccolE(K)
```

**Comment by Pheosics** [comment]
One of them is a check for the sign, the others are checks for negative numbers. We definitely could use sign() for the case you called out, but I chose not to in order to keep it the same as the drift codes in ModRamDrift.f90.

**Comment by drsteve** [comment]
Since you've updated the PARAM.XML here can I check that you regenerated the docs and made sure it worked/looked okay?

(Also, a check for negative numbers is also a sign check... but I get that the exact use is slightly different and makes alternative approaches like using sign a little more messy)

Anyway, if the docs build and pass visual inspection LMK and I'll merge.

**Comment by Pheosics** [comment]
Yes the docs generated fine and looked ok. There is still incorrect information being read in from the other tex files that I need to update. But at least the params are correct.

**Pull request merged**
