### PR TITLE
Add Kpmax12, Kpmax24, replace Kp with KpmaxXX where needed

### PR DESCRIPTION
**Pull request by katmipt**
Changed code in several places:

- indices now are initialized from 24 hours before start time;
- changed *get_indices* to *update_indices* since the subroutine basically updated Kp, F107, AE and it would not be correct to use it to get indices at arbitrary time
- added kpmax12 and kpmax24 to update_indices: max kp during previous 12 and 24 hours
- changed Kp to Kpmax12 & Kpmax24 where needed (Moldwing plasmapause model and Carpenter plasmaphere model)
There is another place with a Carpenter model (plane_scb.f90), I didn't touch it. Is it any different from Carpenter model in ModRamPlasmasphere? Do we need it?

### CODE REVIEW

**Comment by katmipt** [comment]
Old code at the first step doesn't use a point from a previous time and a point from next time, but uses point from next time and time one step further, i.e., Kp = 2.0 (time 2017-03-17&01:30:00), and Kp = 2.3 (time 2017-03-17&04:30:00). This means that dttime is negative (-0.5) and then kpnow = dtime*(rawkp(itime) - rawkp(itime-1)) + rawkp(itime-1) = -0.5*0.3 + 2.0 = 1.85. And this then makes all the output different from the PR's output.

**Comment by Pheosics** [comment]
I never realized it did this (I don't think I ever really looked at the get_indices code before). It looks like we should go ahead with this change and update the tests.

**Comment by drsteve** [comment]
Who wants to run all the tests and update the expected results (in `output/test*`)?

**Comment by drsteve** [comment]
Just to add, the extrapolation backwards in time at the first step in the old code isn't necessarily a bad way of doing it. If you only have the indices for the simulation interval you don't have many ways to work around that hard edge... It's just that it's not accurate and we should (almost) always have indices for the previous day, so having the code actually load that data and interpolate is a good update alongside fixing the 12- and 24-hour maxima.

So once the tests are updated, I think this will be good to merge.

**Review by drsteve — APPROVED** [review]
Looks good and, in addition to the CI test, the full test suite passes locally.
Thanks!

**Pull request merged**
