### PR TITLE
Modifications from RAM-HANE

### PR DESCRIPTION
**Pull request by Pheosics**
These are changes that were added to make RAM-HANE function properly.

### CODE REVIEW

**Comment by drsteve** [comment]
@Pheosics I've nearly worked through the changes... but it's much easier/faster to do that if I have a clearer description of what was changed and why. "Changes to make the code work" isn't really much to go on... 

Also, the tests are no longer running. I believe this is because the LANL group's Travis account has expired (I got an email). I guess they signed up for a free trial that has now expired... it's weird because Travis is free for open-source projects. Anyway, can you let me know which systems you've run the test suite on for now? We'll have to track down who runs the LANL github group so we can get the CI fixed.

**Comment by Pheosics** [comment]
Each commit has a description of what was done, not great ones, but definitely more detailed than the pull request message. I could move the individual commit messages into the pull request message if that would make it easier.

I've run the testing suite on bigiron, everything passed

**Comment by drsteve** [comment]
The commit messages are decent short summaries. Having more description, coupled with additional comments in the code to clarify what's being done, would make it easier to work through though. Especially when some of the commits are very large. 

Still, thanks for the work and the updates on the testing.

**Comment by Pheosics** [comment]
The old Nitrogen cross sections were completely made up, actually I believe they were just a copy of the Strontium cross sections I was using for the other project (first column is velocity). RAM isn't typically run with energies higher than 500 keV so in a typical run it won't have any effect. If someone wanted to run with a higher energy the code would linearly extrapolate the cross section, this could lead to negative or unrealistic cross sections, but for now there isn't much we could do about that since I couldn't find any literature on higher energy cross sections.

I enjoy having the timing stuff being printed, but you are right, it should probably be a verbosity setting, Part of my writing documentation effort is to provide comments to the entire code base. It is in bad need of it (probably also some formatting clean-up, but the comments are more important).

**Comment by drsteve** [comment]
Thanks, if you can hide the printout behind a verbosity flag then I'll merge.
The comments and documentation can wait since you have that underway right now anyway.

**Pull request merged**
